### ISSUE TITLE
readme changes / clarifications

### ISSUE THREAD

**Issue by bgoleno** [mcplusa/cloudfoundry-sumologic-nozzle#1]
--sumo-endpoint=SUMO-ENDPOINT  Complete URL  for the endpoint, copied from the Sumo Logic HTTP Source configuration

--nozzle-polling-period=15s    How frequently this Nozzle polls the CF Firehose for data

--log-events-batch-size=200    Log Events Batch Size to send to Sumo
    <question>:  is this a a trigger that says "when there are X number of message in the buffer, send those to Sumo Logic?  If so, clarify that.  
<question>:  Is this the right default?

--sumo-post-minimum-delay=200ms     Sumo Logic HTTP Post Minimum Delay
   <question>: is this the maximum time that the Nozzle will wait before flushing its contents to Sumo Logic?
   <question>:  Is this the right default?

--sumo-category=""          This value overrides the default "Source Category" associated with the configured Sumo Logic HTTP Source

--sumo-name=""               This value overrides the default "Source Name" associated with the configured Sumo Logic HTTP Source

 --sumo-host=""                 This value overrides the default "Source Host" associated with the configured Sumo Logic HTTP Source

--verbose-log-messages         Allow Verbose Log Messages
<clarify> : what are the values?  true|false ?   What is the difference in outcome between setting either flag?

--custom-metadata=""           Use this flag for addingCustom Metadata (key1:value1,key2:value2, etc...)
<clarify> : Is this adding custom key/value pairs to the messages?  I assume so since there is no other mechanism to do so.

**Comment by sklava** [comment]
Nicole made changes to the readme file.
