### ISSUE TITLE
manifest environment variable error

### ISSUE THREAD

**Issue by cholick** [mcplusa/cloudfoundry-sumologic-nozzle#3]
`manifest.yml` sets the environment variable `LOG_EVENTS_BATCHSIZE` to 200. This is the wrong variable name. Main is parsing `LOG_EVENTS_BATCH_SIZE`.

**Comment by sklava** [comment]
I created a pull request for this change in sumo logic's repo.  https://github.com/SumoLogic/sumologic-cloudfoundry-nozzle
