### ISSUE TITLE
Swallowing errors

### ISSUE THREAD

**Issue by cholick** [mcplusa/cloudfoundry-sumologic-nozzle#6]
`main.go` is swallowing any errors connecting to Cloud Foundry:
```
cfClient, _ := cfclient.NewClient(&c)
```

https://github.com/mcplusa/cloudfoundry-sumologic-nozzle/blob/master/main.go#L81

**Comment by sklava** [comment]
`cfClient, errCfClient := cfclient.NewClient(&c)

	if errCfClient != nil {
		logging.Error.Fatal("Error setting up CF Client: ", errCfClient)
		os.Exit(1)
	}`
master branch
