### ISSUE TITLE
F2S_DISABLE_LOGGING

### ISSUE THREAD

**Issue by cholick** [mcplusa/cloudfoundry-sumologic-nozzle#9]
This flag is inaccurately named and doesn't work.

1. From the description "Handle if the Nozzle logs will be ignored and not send to Sumo Logic". This flag is setting when looking up app caching data, which is only a subset of messages, and so the description isn't accurate - it would only filter app messages
1. It also doesn't work at all. There's no branching in the appender when it sends to Sumo that checks the flag.

**Comment by sklava** [comment]
Flag does not exist in the master branch code.
